name: chat_firstdemo_app
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.6 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: ^2.10.0
  google_sign_in: ^6.1.0
  firebase_auth: ^4.4.2
  cloud_firestore: ^4.5.3
  cached_network_image: ^3.2.3
  image_picker: ^0.8.7+4
  firebase_storage: ^11.1.2
  emoji_picker_flutter: ^1.5.4
  http: ^0.13.6

  # Get current device information.
  device_info_plus: ^9.0.0

  #accessing firebase messaging (push notification)
  firebase_messaging: ^14.6.1

  #for notification channel_talk_flutter
  flutter_notification_channel: ^2.0.0

  #for storing images to gallery
  gallery_saver: ^2.3.2

  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - images/
  uses-material-design: true

